**Libraries**

In [1]:
import pandas as pd

**Load Dataset and View**

In [4]:
df=pd.read_csv("/content/ai4i2020.csv")
df['Type'].head()

0    M
1    L
2    L
3    L
4    L
Name: Type, dtype: object

**One Hot Encoding**

In [16]:
dummies=pd.get_dummies(df['Type'])
dummies.head()

       H      L      M
0  False  False   True
1  False   True  False
2  False   True  False
3  False   True  False
4  False   True  False

**Merge dummy columns**

In [7]:
merged=pd.concat([df,dummies],axis='columns')
merged.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,H,L,M
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,False,False,True
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,False,True,False
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,False,True,False
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,False,True,False
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,False,True,False

**Drop unecessary columns**

In [12]:
final=merged.drop('Type',axis='columns')

**Drop dummy column**

In [13]:
final=final.drop('M',axis='columns')
final.head()

,UDI,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,H,L
0,1,M14860,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,False,False
1,2,L47181,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,False,True
2,3,L47182,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,False,True
3,4,L47183,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,False,True
4,5,L47184,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,False,True

**All these above steps can be done in single step:**
(one hot encoding, merge, drop unecessary columns)
```
dummies=pd.get_dummies(df,columns=['Type'],drop_first=True)
```

*drop_first=True*  **is to avoid dummy trap**

**Save the clean dataset**

In [14]:
final.to_csv('encoded_factory_data.csv', index=False)